version: '3.8'

services:
  telegram-bot:
    build: .
    ports:
      - "5000:5000"
    environment:
      - TELEGRAM_TOKEN=7883497770:AAFRVc8DKBofRkdy6m0EGdpkaoOJz10Qw8E
      - PORT=5000
    restart: unless-stopped